#!/usr/bin/env node
/**
 * CocoPlus SessionEnd hook — cross-platform (Node.js)
 * Fires when Coco ends a session.
 * Responsibilities: finalize CocoMeter, flush memory buffer, update AGENTS.md.
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const { isoUtc, appendJsonLine, atomicWrite, logError, readJsonString, readJsonNumber } = require('./_common.js');

const COCOPLUS_DIR = '.cocoplus';
const HOOK_LOG     = path.join(COCOPLUS_DIR, 'hook-log.jsonl');

function main() {
  if (!fs.existsSync(COCOPLUS_DIR)) return;

  const ts        = isoUtc();
  const sessionId = process.env.COCO_SESSION_ID || 'unknown';

  appendJsonLine(HOOK_LOG, { hook: 'session-end', session: sessionId, ts });

  // 1. Finalize CocoMeter
  if (fs.existsSync(path.join(COCOPLUS_DIR, 'modes', 'cocometer.on'))) {
    const meterFile   = path.join(COCOPLUS_DIR, 'meter', 'current-session.json');
    const historyFile = path.join(COCOPLUS_DIR, 'meter', 'history.jsonl');

    if (fs.existsSync(meterFile)) {
      const startedAt = readJsonString(meterFile, 'started_at');
      const phase     = readJsonString(meterFile, 'phase');
      const tools     = readJsonNumber(meterFile, 'tools_called');
      const tokens    = readJsonNumber(meterFile, 'tokens_consumed');
      const sql       = readJsonNumber(meterFile, 'sql_statements');
      const writes    = readJsonNumber(meterFile, 'writes_performed');

      const record = { session_id: sessionId, started_at: startedAt, ended_at: ts, phase, tools_called: tools, tokens_consumed: tokens, sql_statements: sql, writes_performed: writes };

      // Dedupe: only append if this session_id is not already in history
      let alreadyLogged = false;
      if (fs.existsSync(historyFile)) {
        const lines = fs.readFileSync(historyFile, 'utf8').split('\n').filter(Boolean);
        alreadyLogged = lines.some(l => {
          try { return JSON.parse(l).session_id === sessionId; } catch (_) { return false; }
        });
      }
      if (!alreadyLogged) {
        appendJsonLine(historyFile, record);
      }

      try { fs.unlinkSync(meterFile); } catch (_) { /* ignore */ }
      appendJsonLine(HOOK_LOG, { hook: 'session-end', action: 'meter_finalized', session: sessionId, ts });
    }
  }

  // 2. Flush memory decision buffer
  if (fs.existsSync(path.join(COCOPLUS_DIR, 'modes', 'memory.on'))) {
    const bufferFile   = path.join(COCOPLUS_DIR, '.decision-buffer');
    const decisionsFile = path.join(COCOPLUS_DIR, 'memory', 'decisions.md');

    if (fs.existsSync(bufferFile)) {
      const buf = fs.readFileSync(bufferFile, 'utf8').trim();
      if (buf) {
        fs.appendFileSync(decisionsFile, `\n## Session ${sessionId} - ${ts}\n${buf}\n`);
        try { fs.unlinkSync(bufferFile); } catch (_) { /* ignore */ }
        appendJsonLine(HOOK_LOG, { hook: 'session-end', action: 'memory_flushed', session: sessionId, ts });
      }
    }
  }

  // 3. Refresh AGENTS.md with current state
  const metaPath = path.join(COCOPLUS_DIR, 'lifecycle', 'meta.json');
  const phase = fs.existsSync(metaPath) ? (readJsonString(metaPath, 'current_phase') || 'unknown') : 'unknown';

  let modesList = '';
  const modesDir = path.join(COCOPLUS_DIR, 'modes');
  if (fs.existsSync(modesDir)) {
    const flags = fs.readdirSync(modesDir).filter(f => fs.statSync(path.join(modesDir, f)).isFile());
    modesList = flags.map(f => `- ${f}`).join('\n') || '- (none active)';
  }

  let recentDecisions = '(None recorded)';
  const decisionsPath = path.join(COCOPLUS_DIR, 'memory', 'decisions.md');
  if (fs.existsSync(decisionsPath)) {
    const lines = fs.readFileSync(decisionsPath, 'utf8').split('\n').filter(l => l.startsWith('-'));
    recentDecisions = lines.slice(-3).join('\n') || '(None recorded)';
  }

  atomicWrite(path.join(COCOPLUS_DIR, 'AGENTS.md'), [
    '# AGENTS.md — Active Personas & Session State',
    '# Auto-generated by session-end hook. Keep ≤200 lines.',
    '',
    '## Current Session',
    `Ended: ${ts}`,
    `Session ID: ${sessionId}`,
    '',
    '## CocoBrew Lifecycle',
    `Phase: ${phase}`,
    '',
    '## Active Modes',
    modesList,
    '',
    '## Recent Decisions',
    recentDecisions,
  ].join('\n'));
}

try {
  main();
} catch (err) {
  logError('session-end', err.message);
}
