CREATE OR REPLACE CORTEX SEARCH SERVICE MEDNOTES_SEARCH_SERVICE
  ON TEXT
  ATTRIBUTES ADMISSION_TYPE, DIAGNOSIS
  WAREHOUSE = HOL_WH
  TARGET_LAG = '30 day'
  AS (
    SELECT
        SUBJECT_ID,
        ROW_ID,
        HADM_ID,
        CATEGORY,
        ADMISSION_TYPE,
        DIAGNOSIS,
        TEXT,
        AGE,
        GENDER,
        LOS
    FROM MEDICAL_NOTES
);